#pragma once

enum BlendFactor
{
  BLEND_ZERO,
  BLEND_ONE,
  BLEND_SRC_COLOR,
  BLEND_INV_SRC_COLOR,
  BLEND_SRC_ALPHA,
  BLEND_INV_SRC_ALPHA,
  BLEND_DEST_ALPHA,
  BLEND_INV_DEST_ALPHA,
  BLEND_DEST_COLOR,
  BLEND_INV_DEST_COLOR,
  BLEND_SRC_ALPHA_SAT,
  BLEND_BLEND_FACTOR,
  BLEND_INV_BLEND_FACTOR,
  BLEND_SRC1_COLOR,
  BLEND_INV_SRC1_COLOR,
  BLEND_SRC1_ALPHA,
  BLEND_INV_SRC1_ALPHA
};

enum BlendOp
{
  BLEND_OP_ADD,
  BLEND_OP_SUBTRACT,
  BLEND_OP_REV_SUBTRACT,
  BLEND_OP_MIN,
  BLEND_OP_MAX
};
