#include "Graphics/DepthCompareOp.h"
#include "Reflection/ReflectionImplMacros.h"

REFLECT_ENUM_BEGIN(DepthCompareOp)
REFLECT_ENUM_VALUE(NEVER)
REFLECT_ENUM_VALUE(LESS)
REFLECT_ENUM_VALUE(EQUAL)
REFLECT_ENUM_VALUE(LESS_OR_EQUAL)
REFLECT_ENUM_VALUE(GREATER)
REFLECT_ENUM_VALUE(NOT_EQUAL)
REFLECT_ENUM_VALUE(GREATER_OR_EQUAL)
REFLECT_ENUM_VALUE(ALWAYS)
REFLECT_ENUM_END(DepthCompareOp)
